### ISSUE TITLE
Uncaught ReferenceError: $ is not defined at three-waves.min.js:1

### ISSUE THREAD

**Issue by eternity6666** [theme-next/theme-next-three#5]
When I use theme-next-three in next, I meet this problem.
The path of ```three-waves.min.js``` is ```themes/next/source/lib/three/three-waves.min.js```.

**Comment by stevenjoezhang** [comment]
Fixed in https://github.com/theme-next/theme-next-three/commit/941060002b98395a31cb47a33166f5568a20d4b5
